### ISSUE TITLE
How do i implement the view?

### ISSUE THREAD

**Issue by afidegnum** [silverapp/silver#590]
Hi 

I m new to Django, i have created models being product and orders, how do i create the views to use silver payments? i can see all links are REST API is there a way to integrate this in a views? can you please through more light ?

**Comment by bogdanpetrea** [comment]
Hi @afidegnum,

Sorry for the late response.
The recommended way would be to write the frontend using a modern javascript framework (such as ReactJS, or VueJS), at least that's what we chose to do. We've also added an authorization layer between the frontend and the Silver server, so that exposed Silver resources (transactions, invoices, payment methods...) would be separated per each customer.

Another way would be to implement your own Django views and write your custom logic, based on the existing Silver models.

Whatever method you choose, if you are inexperienced I would recommend you to follow some tutorials first.
