### ISSUE TITLE
Multiple invoice templates

### ISSUE THREAD

**Issue by lucifurtun** [silverapp/silver#658]
Is there any way to choose a specific template when adding a new invoice?

**Comment by bogdanpetrea** [comment]
Not really...

One place where you can do this right now is in the actual invoice template:
```html
{% if document.meta.custom_template is True %}
    {% include "_custom_invoice_template.html" %}
{% else %}
    {% include "_invoice_template.html" %}
{% endif %}
```

Currently there is no place where you can hook into the logic that decides what template will be used for rendering.
You could override the `get_template` [method](https://github.com/silverapp/silver/blob/a2dc11cb10af95bc7b2c6f49f9c18507d6261e1c/silver/models/documents/base.py#L466) directly in your `models.py` file, but it's not so nice:
```python
from silver.models.documents import BillingDocumentBase

def get_template(doc, state=None):
    // custom logic here
BillingDocumentBase.get_template = get_template
```

**Comment by lucifurtun** [comment]
@bogdanpetrea, do you think it makes sense to have such feature exposed to the client?

**Comment by bogdanpetrea** [comment]
If you'd be willing to describe your use case a bit, it might make sense.

**Comment by lucifurtun** [comment]
@bogdanpetrea, sure. Let's say you have a `Provider` that needs to issue invoices for some `Customer`s using one template but for other `Customer`s using some other template. How would you solve this issue?

**Comment by bogdanpetrea** [comment]
If you know what customers require special treatment beforehand, you could just code it in your billing app (see [my previous comment](https://github.com/silverapp/silver/issues/658#issuecomment-518224434)). You could override the `get_template` method and read the template name that should be used from `customer.meta`. 

In both cases you are required to define the custom templates in your app beforehand. Otherwise it gets complicated... I don't know if there's any app that lets you submit templates via Django admin. The first thing that comes to mind is arbitrary code execution.
